const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const config=require('../../../config/pmg-yard-prices.json');
const source=fs.readFileSync(require.resolve('../../../scripts/haultech-agreed-pricing.cjs'),'utf8').replace('module.exports={evaluateAgreedPrice};','')+'\n'+fs.readFileSync(require.resolve('../worker/agreed-evidence-producer.js'),'utf8')+'\n'+fs.readFileSync(require.resolve('../worker/agreed-pricing-adapter.js'),'utf8');
const clone=x=>JSON.parse(JSON.stringify(x));let history=[],writes=0,record,kv=new Map();
const fixture=()=>({id:'job',jobId:12001,customerId:'generic-known-account',quotedPrice:0,totalPrice:0,useQuotedPrice:false,active:true,deliveryStatus:'Completed',deliveryDate:'2026-10-02T00:00:00Z',deliveryVehicleId:'eight-id',deliveryLoadId:'load',trafficNotes:'legitimate site note',accountNotes:'',consignments:[{id:'c',goodsDescription:'6F2 Crush',weight:20,quantity:20,invoicedCount:0,invoiceExportCount:0,deliveryAddressLine1:'1 Test Road',deliveryPostcode:'FY6 9DJ'}]});record=fixture();
const sandbox={AGREED_COMPLETION_POLICY:config.haultech_completion_policy,AGREED_CATALOGUE:config,Date,Intl,AbortSignal,encodeURIComponent,PM_GROUNDWORKS_CUSTOMER_ID:'pmg',DRIVER_APP_VEHICLE_IDS_BY_REG:{PN25AMU:'eight-id'},jobHasExistingPrice:j=>[j.quotedPrice,j.totalPrice].some(n=>n!==0),cleanText:v=>v||'',jobCustomerId:j=>j.customerId,jobGoodsDescription:j=>j.consignments[0].goodsDescription,jobCustomerReference:j=>j.customerReference||'',firstConsignment:j=>j.consignments[0],jobQuantity:j=>j.consignments[0].weight,isDeliveredConcreteJob:j=>false,normalisedLookupText:v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),normalisedCompletionMaterial:j=>j.consignments[0].goodsDescription.toLowerCase(),normaliseUkPostcode:v=>v,normalisedStatus:v=>v.toLowerCase(),htFetch:async(_env,path,options)=>{if(path.includes('GetOldInvoices'))return {ok:true,json:async()=>history};if(path.includes('UpsertJob')){writes++;record=JSON.parse(options.body);record.consignments[0]._etag='fresh';return {ok:true};}throw Error(path);},fetchHaultechJobsByDate:async()=>({ok:true,jobs:[clone(record)]}),fetch:async(url)=>({ok:true,json:async()=>url.includes('postcodes.io')?{result:{longitude:-2.95,latitude:53.88}}:{code:'Ok',routes:[{duration:1500.01}]}})};
vm.runInNewContext(source,sandbox);sandbox.completionAutoPrice=(j,q,e)=>sandbox.agreedCompletionAutoPrice(j,q,e);
const env={PMG_DATA:{get:async k=>kv.get(k)||null,put:async(k,v)=>kv.set(k,JSON.parse(v))}};
(async()=>{
 let evidence=await sandbox.deriveAgreedEvidence(record,20,env);assert.equal(evidence.facts.kind,'6f2_delivered');
 let result=await sandbox.verifiedAgreedReprice(env,clone(record),'2026-10-02');assert.equal(result.status,'verified');assert.equal(record.quotedPrice,250);assert.equal(record.trafficNotes,'legitimate site note');assert.equal(writes,1);
 result=await sandbox.verifiedAgreedReprice(env,clone(record),'2026-10-02');assert.equal(result.status,'preserved_existing_price');assert.equal(writes,1);
 record=fixture();history=[{invoiceId:1}];result=await sandbox.verifiedAgreedReprice(env,clone(record),'2026-10-02');assert.equal(result.status,'invoice_history_hold');assert.equal(writes,1);
 history=[];record=fixture();record.consignments[0].weight=19;result=await sandbox.deriveAgreedEvidence(record,19,env);assert.equal(result,null);
 record=fixture();record.customerId=config.haultech_completion_policy.protected_agreements[0].customer_id;record.consignments[0].deliveryAddressLine1='Norcross Lane';evidence=await sandbox.deriveAgreedEvidence(record,20,env);assert.equal(evidence.facts.agreement.amount,235);
 record.consignments[0].deliveryAddressLine1='Future Site';assert.equal(await sandbox.deriveAgreedEvidence(record,20,env),null);
 record=fixture();record.deliveryStatus='Scheduled';result=await sandbox.verifiedAgreedReprice(env,record,'2026-10-02');assert.equal(result.status,'awaiting_actual_completion');
 console.log('8 pipeline checks passed: live-field derivation, write/readback, idempotency, invoice exclusion, unsupported quantities, exact site agreement, future-site hold, planned-job hold');
})().catch(e=>{console.error(e);process.exit(1)});
